import { Metadata } from "next";
import { Inter} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ['latin']})
require('dotenv').config();



export const metadata = {
  title: "Inicio-Caproluz",
  description: "Generated by create next app",
  
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
     
      <body className={`${inter.className} antialiased `}>  
        
          {children}
          
        </body>
    </html>
    
  );
}
